FROM golang:1.22 AS builder


RUN apt-get update && apt-get install -y \
    librdkafka-dev \
    gcc \
    g++


WORKDIR /src
COPY . .


# Build API
RUN go build -o evaluator ./evaluators

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /src/evaluator . 
RUN chmod +x evaluator

COPY --from=builder /src/evaluators/configs/*.json .

