FROM golang:1.22 AS builder

RUN apt-get update && apt-get install -y \
    librdkafka-dev \
    gcc \
    g++


WORKDIR /src
COPY . .



# Build API
RUN go build -o eval-api ./api


FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /src/eval-api .
COPY --from=builder /src/api/config.json .

